routes/web.php
<?php

use App\Http\Controllers\TodoController;
use App\Http\Controllers\ToggleTodoState;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return to_route('todos.index');
});

Route::resource('todos', TodoController::class)->only(['index', 'store', 'destroy']);
Route::post('todos/{todo}/toggle', ToggleTodoState::class)->name('todos.toggle');

app/Models/Todo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Todo extends Model
{
    use HasFactory;
    use SoftDeletes;

    /**
     * {@inheritdoc}
     */
    protected $fillable = [
        'description',
    ];

    /**
     * Determine if the todo is completed.
     *
     * @return bool
     */
    public function isCompleted(): bool
    {
        return ! is_null($this->done_at);
    }

    /**
     * Toggle the todo state.
     *
     * @return $this
     */
    public function toggle(): static
    {
        $this->isCompleted() ? $this->markAsPending() : $this->markAsCompleted();

        return $this;
    }

    /**
     * Mark the todo state as pending.
     *
     * @return bool
     */
    public function markAsPending(): bool
    {
        return $this->forceFill([
            'done_at' => null,
        ])->save();
    }

    /**
     * Mark the todo state as completed.
     *
     * @return bool
     */
    public function markAsCompleted(): bool
    {
        return $this->forceFill([
            'done_at' => $this->freshTimestamp(),
        ])->save();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/TodoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTodoRequest;
use App\Models\Todo;

class TodoController
{
    /**
     * Display a listing of the todos.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('todos.index', [
            'todos' => Todo::query()->latest()->get(),
        ]);
    }

    /**
     * Store a newly created todo in storage.
     *
     * @param  \App\Http\Requests\StoreTodoRequest  $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreTodoRequest $request)
    {
        Todo::create($request->validated());

        return to_route('todos.index');
    }

    /**
     * Remove the specified todo from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(int $id)
    {
        tap(Todo::query()->findOrFail($id), fn(Todo $todo) => $todo->delete());

        return to_route('todos.index');
    }
}

app/Http/Controllers/ToggleTodoState.php
<?php

namespace App\Http\Controllers;

use App\Models\Todo;

class ToggleTodoState
{
    /**
     * Toggle the state of the specified todo.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function __invoke(int $id)
    {
        tap(Todo::query()->findOrFail($id), fn(Todo $todo) => $todo->toggle());

        return to_route('todos.index');
    }
}

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Todo App</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body class="bg-teal-100">
        @yield('content')
    </body>
</html>

resources/views/todos/index.blade.php
@php
    /**
     * @var \Illuminate\Database\Eloquent\Collection<int, App\Models\Todo> $todos
     */
@endphp

@extends('layouts.main')

@section('content')
    <div class="flex items-center justify-center font-sans">
        <div class="bg-white rounded shadow p-6 mt-8 w-3/4">
            <div class="mb-10">
                <h1 class="text-gray-900">Todo List</h1>
                <form action="{{ route('todos.store') }}" method="POST" class="flex mt-4">
                    @csrf
                    <div class="flex-grow mr-4">
                        <input
                            class="block shadow appearance-none border rounded w-full py-2 px-3 text-gray-900"
                            name="description" placeholder="Add Todo"
                            value="{{ old('description') }}">

                        @error('description')
                            <span class="text-red-600 text-sm mt-40">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <button class="flex-shrink-0 p-2 border-2 rounded text-teal-500 border-teal-500 hover:text-white hover:bg-teal-500">
                        Add
                    </button>
                </form>
            </div>
            <div>
                @foreach($todos as $todo)
                    <div class="flex mb-4 items-center">

                        <p @class([
                            'w-full text-gray-900',
                            'line-through text-green-500' => $todo->isCompleted(),
                        ])>{{ $todo->description }}</p>

                        <form action="{{ route('todos.toggle', $todo) }}" method="POST" class="flex-shrink-0 ml-4 mr-2">
                            @csrf

                            @if($todo->isCompleted())
                                <button
                                    class="p-2 border-2 rounded hover:text-white text-gray-500 border-gray-500 hover:bg-gray-500">
                                    Not Done
                                </button>
                            @else
                                <button
                                    class="p-2 border-2 rounded hover:text-white text-green-500 border-green-500 hover:bg-green-500">
                                    Done
                                </button>
                            @endif
                        </form>

                        <form action="{{ route('todos.destroy', $todo) }}" method="POST" class="flex-shrink-0 ml-2">
                            @csrf
                            @method('DELETE')
                            <button type="submit"
                                class="p-2 border-2 rounded text-red-500 border-red-500 hover:text-white hover:bg-red-500">
                                Remove
                            </button>
                        </form>

                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection